### PR TITLE
Do not re-load new users

### PR DESCRIPTION
**Pull request by sobolev-alexey**
As per task requirement:
```When you navigate to the previous page with a list of people, it should not load new profiles, but keep the previous profiles in place. ```
So you need to check if users were already persisted before you initiate loading of the new users

### CODE REVIEW

**Comment by karimkozman** [comment]
Hi Alexey,

In HomePage.js,  I'm adding the users to the state in mapStateToProps. And in store.js I put my redux store in PersistStore and I wrapped my App component in PersistGate while passing the persistor props in index.js. so the users are persisted and the app doesn't reload new users when you refresh the page or go to the previous page from the ProfilePage. It's working fine and the users are persisted on my end.

________________________________

**Comment by karimkozman** [comment]
I'm using redux logger and I just checked again, in the previous state the persist is working and the values in the array of users are the same as the next state.

If there's still an issue, please let me know.

Regards,
Karim
________________________________

**Comment by sobolev-alexey** [comment]
Hi Karim,

thanks for your comments. 
The PersistStore works, when you already retrieved and persisted users once. 
I would encourage you to run the following test case: 
* Clear browser's local storage with `localStorage.clear()`
* Clear browser cache or open new tab in Incognito mode.
* Restart the react start script and navigate to http://localhost:3000

You will see that users are being loaded but not stored.

Best,
Alexey

**Comment by karimkozman** [comment]
I figured what's the problem. So I changed localStorage to sessionStorage so that fixes the issue of reloading new users.
________________________________

**Pull request merged**
